version: '2'
services:
    octomusprime-app:
        image: octomusprime
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://octomusprime-postgresql:5432/OctomusPrime
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    octomusprime-postgresql:
        extends:
            file: postgresql.yml
            service: octomusprime-postgresql
